//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrola_Domowego_Budzetu.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] Scan { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ShopName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PaymentDay { get; set; }
        public string BuyerName { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
