//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrola_Domowego_Budzetu.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public string ParentCategory { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public int ProductId { get; set; }
    }
}
